package com.cdy.cms.settings.mapper;

import com.cdy.cms.settings.pojo.Teacher;

import java.util.Map;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    int deleteByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    Teacher selectByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    int updateByPrimaryKey(Teacher record);

    Teacher queryUserByJobNumAndPwd(Map<String,Object> map);

}