package com.cdy.cms.settings.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.full_name
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_number
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.examine_state
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String examineState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.login_pwd
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    private String loginPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.full_name
     *
     * @return the value of student.full_name
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.full_name
     *
     * @param fullName the value for student.full_name
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_number
     *
     * @return the value of student.student_number
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_number
     *
     * @param studentNumber the value for student.student_number
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber == null ? null : studentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.examine_state
     *
     * @return the value of student.examine_state
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getExamineState() {
        return examineState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.examine_state
     *
     * @param examineState the value for student.examine_state
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setExamineState(String examineState) {
        this.examineState = examineState == null ? null : examineState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param createTime the value for student.create_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_time
     *
     * @return the value of student.update_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_time
     *
     * @param updateTime the value for student.update_time
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.login_pwd
     *
     * @return the value of student.login_pwd
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.login_pwd
     *
     * @param loginPwd the value for student.login_pwd
     *
     * @mbggenerated Tue Apr 04 08:17:36 CST 2023
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }
}