package com.cdy.cms.settings.pojo;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_id
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.full_name
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gender
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_job_number
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String teacherJobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.position
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.examine_state
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String examineState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.create_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.update_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.login_pwd
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    private String loginPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_id
     *
     * @return the value of teacher.teacher_id
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_id
     *
     * @param teacherId the value for teacher.teacher_id
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.full_name
     *
     * @return the value of teacher.full_name
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.full_name
     *
     * @param fullName the value for teacher.full_name
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gender
     *
     * @return the value of teacher.gender
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gender
     *
     * @param gender the value for teacher.gender
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_job_number
     *
     * @return the value of teacher.teacher_job_number
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getTeacherJobNumber() {
        return teacherJobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_job_number
     *
     * @param teacherJobNumber the value for teacher.teacher_job_number
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setTeacherJobNumber(String teacherJobNumber) {
        this.teacherJobNumber = teacherJobNumber == null ? null : teacherJobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.position
     *
     * @return the value of teacher.position
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.position
     *
     * @param position the value for teacher.position
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.examine_state
     *
     * @return the value of teacher.examine_state
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getExamineState() {
        return examineState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.examine_state
     *
     * @param examineState the value for teacher.examine_state
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setExamineState(String examineState) {
        this.examineState = examineState == null ? null : examineState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.create_time
     *
     * @return the value of teacher.create_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.create_time
     *
     * @param createTime the value for teacher.create_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.update_time
     *
     * @return the value of teacher.update_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.update_time
     *
     * @param updateTime the value for teacher.update_time
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.login_pwd
     *
     * @return the value of teacher.login_pwd
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.login_pwd
     *
     * @param loginPwd the value for teacher.login_pwd
     *
     * @mbggenerated Mon Apr 10 15:29:21 CST 2023
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }
}